#!/usr/bin/env python3
"""
Usage: cmdxml [--command CMD] [--script SCRIPT] [--url URL] [...]

custom options:
  --command=command     Command to test, can be specified multiple times
  --script=script       Script to test, can be specified multiple times
  --url=url             Url to script, format: url;sha1=HASH

other options from pytest
"""

import os
import sys

import pytest

import pytest_cmdxml

PLUGINS = [pytest_cmdxml.__name__]
REPORT = 'report.xml'

DEFAULT_ARGS = [
    '--verbosity=1',
    '--junit-xml=%s' % REPORT,
    '--tb=short',
] + pytest_cmdxml.PYTEST_ARGS


def main():
    """Execute pytest with our base configuration."""
    args = DEFAULT_ARGS + sys.argv[1:]
    return pytest.main(args, plugins=PLUGINS)


if __name__ == '__main__':
    sys.exit(main())
